version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: server
    ports:
      - "3000:3000"
    volumes: 
      - .:/lxcacao-server
      - node_modules:/lxcacao-server/node_modules
    command: yarn start-server

volumes:
  node_modules: