version: 2.1
jobs:
  build:
    docker:
      - image: yevskro/cci-lxcacaoserver-docker-primary:0.0.1
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

    working_directory: ~/lxcacao-server

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Create tables
          command: psql -h localhost -U postgres -d testdb -f src/db/create.sql

      - run:
          name: Seed database
          command: psql -h localhost -U postgres -d testdb -f src/db/seed.sql

      - run:
          name: Running tests
          command: yarn ci:test
