version: 2.1
jobs:
  build:
    docker:
      - image: circleci/postgres:11-alpine-ram
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: testdb
    
    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
        name: Waiting for Postgres to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres && exit 1
